/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.main;

import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main( String[] args){
        /*try{
            LocalDatabase.clearTable("states_positive");
        }
        catch(SQLException e){
            e.printStackTrace();

        }*/
        Board board = new Board();
        Predictor p1 = new Predictor(7, (short)1);
        p1.nextColumn(board);
    }
       
    
}
